<center><h1> Uvod u podatkovnu znanost  </h1></center>
<center><h2> Zimski semestar - 2022 </h2></center> 
<center><h3> Lab 2</h3></center> 
<center><h3> </h3></center> 
<center><h3> NumPy, Matplotlib</h3></center> 



## NUMPY

### Instalacija
Na Google colab numpy je već instaliran

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 14.8 MB 3.1 MB/s            ��██████████████████████▌      | 11.8 MB 3.1 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


### Import

The alias `np` je konvencija koje većinom upotrebljava

In [1]:
import numpy as np

### [1] Kreiranje array-a 

Niz iz liste

In [2]:
my_list = [i for i in range(36)]
np_array = np.array(my_list)

In [3]:
np_array.__class__

numpy.ndarray

In [4]:
np_array.shape

(36,)

In [5]:
np_array.dtype

dtype('int64')

In [6]:
np_array.itemsize

8

In [7]:
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
np_array.astype(np.float64)

In [ ]:
np.array([12,0,3,4,5,0,6,7,0],dtype=np.bool_)

Niz iz liste

In [8]:
np.array([1, 2, 3])

array([1, 2, 3])

Niz nula

In [9]:
np.zeros(3)

array([0., 0., 0.])

Niz jedinica

In [ ]:
np.ones(3)

Niz od 3 nasumična int broja između 1 i 10


```
randint(start,end,number_of_values) - number_of_values u interavlu [start,end)
```



In [ ]:
np.random.randint(1,10, 3)

Niz iz 'range-a' integera

In [ ]:
np.arange(1, 100, 5)

Niz linearno udaljenih brojeva

In [ ]:
np.linspace(0, 10, 5 )

Jednostavan 2D niz

In [ ]:
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

Alternativni način za specificiranje višedimenzionalnih nizova

In [ ]:
np.matrix('1 2; 3 4')

Niz sa vrijednostima između 0 i 1

In [ ]:
np.random.random((3,4))

Niz sa normalno distribuiranim elementima

In [ ]:
np.random.randn(3,4)

Primjer nizova: 1D niz a te 2D niz b


In [58]:
b = np.random.randint(0,10, (3,3,3))

print(b)

[[[8 4 8]
  [4 4 9]
  [4 6 6]]

 [[3 7 7]
  [8 1 2]
  [8 0 1]]

 [[5 8 2]
  [4 8 3]
  [4 1 5]]]


Oblik i dimenzija nizova

In [ ]:
print("Shape of a:", np.shape(a))
print("Shape of b:", np.shape(b))

print('Dimension of a:', np.ndim(a))
print('Dimension of b:', np.ndim(b))

Broj elemenata

In [ ]:
print('Number of elements in a:', np.size(a))
print('Number of elements in b:', np.size(b))

### [2] Indeksiranje

Prvi element od a

In [ ]:
print(a[0])
print(a[-4])

Zadnji element od a

In [ ]:
print(a[-1])
print(a[3])

Prvi redak od b

In [ ]:
print(b[0]) 
print(b[0,:])

Drugi stupac od b

In [ ]:
b[:,1]

Dva nova niza

In [ ]:
x = np.array(['a', 'b', 'c'])
y = np.array([['d','e','f'], 
              ['g', 'h', 'k']])

print(x)
print(y)

Indeksiranje 'c' iz x

In [ ]:
ind = [2]
x[ind]

### [3] Slicing


Primjer integera između 1 i 10

In [ ]:
X = np.arange(1, 11, dtype=int)
X

Prva dva elementa od X

In [ ]:
X[:2]

Elementi iz sredine = 3, 4, 5

In [ ]:
X[2:5]

Samo neparni redni brojevi

In [ ]:
X[::2]

Parni redni brojevi

In [ ]:
X[1::2]

Primjer 2D niza

In [ ]:
Y= np.arange(1,10).reshape(3,3)
Y

Prvi i drugi red


In [ ]:
Y[:2,:]

Drugi i treći stupac

In [ ]:
Y[:, 1:]

Parcijalni redak : 5, 6


In [ ]:
Y[1,1:]

### [4] Univerzalne funkcije (ufuncs)
**Brze operacije na nizovima**

In [ ]:
X

Maximum element

In [ ]:
np.max(X)

Mean svih elemenata

In [ ]:
np.mean(X)

Svi elementi na potenciju broja 4


In [ ]:
np.power(X, 4)

Trigonometrijske funkcije

In [ ]:
print(np.sin(X))
print(np.tan(X))

Računanje $(sin \; x_{ij})^2 + (cos \; x_{ij})^2$ za svaki element

In [ ]:
# x2 + y2 = 1
np.square(np.sin(X)) + np.square(np.cos(X))

2D niz

In [ ]:
Y

Množenje svakog elementa

In [ ]:
np.multiply(Y, 2)

Split Y u 3 podniza

In [ ]:
np.split(Y, 3)

### [5] Broadcasting

 Broadcasting oredstavlja mogućnost korištenja ufuncs i mnogih drugih operacija na nizove različitih nizova

In [ ]:
X

Dodavanje 5 na svaki element

In [ ]:
X + 5

In [ ]:
np.add(X, 5)

Niz Z sa newaxis

In [ ]:
Z = np.arange(3)[:, np.newaxis]
Z

In [ ]:
Z.shape

In [ ]:
Y.shape

In [ ]:
np.multiply(Y, Z)

In [ ]:
np.matmul(Y, Z)

### [6] Druge operacije

In [ ]:
x = np.random.randint(1,5, 10)
x

In [ ]:
y = np.random.randint(1,5, (3,3))
y

Sortiranje

In [ ]:
np.sort(x)

Sortiranje po redcima

In [ ]:
np.sort(y, axis=0)

Sortiranje po stupcima

In [ ]:
np.sort(y, axis=1)

Conditions primijenjen na nizove

In [ ]:
# == , !=, < , >, >=, <= operations on arrays
x > 3

Maskiranje niza

In [ ]:
x[x>3]

In [ ]:
x[(x <= 3) & (x>1)]

## MATPLOTLIB

### Instalacija

In [ ]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
     |████████████████�███            | 7.2 MB 2.5 MB/s eta 0:00:02�███▉                        | 2.8 MB 2.5 MB/s eta 0:00:04

### Import

In [2]:
import matplotlib.pyplot as plt

### [1] Line Plots

In [ ]:
x = np.linspace(0,10)
plt.plot(x)
plt.show()

In [ ]:
x = np.linspace(0,10)
y = np.exp(x)
plt.plot(x,y)
plt.show()

In [ ]:
x  = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y1 = [1, 3, 5, 3, 1, 3, 5, 3, 1]
y2 = [2, 4, 6, 4, 2, 4, 6, 4, 2]
plt.plot(x, y1, label="line L")
plt.plot(x, y2, label="line H")
plt.plot()

plt.xlabel("x axis")
plt.ylabel("y axis")
plt.title("Line Graph Example")
plt.legend()
plt.show()

### [2] Bar Plots

In [ ]:
# Look at index 4 and 6, which demonstrate overlapping cases.
x1 = [1, 3, 4, 5, 6, 7, 9]
y1 = [4, 7, 2, 4, 7, 8, 3]

x2 = [2, 4, 6, 8, 10]
y2 = [5, 6, 2, 6, 2]

# Colors: https://matplotlib.org/api/colors_api.html

plt.bar(x1, y1, label="Blue Bar", color='b')
plt.bar(x2, y2, label="Green Bar", color='g')
plt.plot()

plt.xlabel("bar number")
plt.ylabel("bar height")
plt.title("Bar Chart Example")
plt.legend()
plt.show()

### [3] Histograms

In [ ]:
# Use numpy to generate a bunch of random data in a bell curve around 5.
n = 5 + np.random.randn(1000)

m = [m for m in range(len(n))]
plt.bar(m, n)
plt.title("Raw Data")
plt.show()

plt.hist(n, bins=20)
plt.title("Histogram")
plt.show()

plt.hist(n, cumulative=True, bins=20)
plt.title("Cumulative Histogram")
plt.show()

### [4] Scatter Plots

In [ ]:
x1 = [2, 3, 4]
y1 = [5, 5, 5]

x2 = [1, 2, 3, 4, 5]
y2 = [2, 3, 2, 3, 4]
y3 = [6, 8, 7, 8, 7]

# Markers: https://matplotlib.org/api/markers_api.html

plt.scatter(x1, y1)
plt.scatter(x2, y2, marker='v', color='r')
plt.scatter(x2, y3, marker='^', color='m')
plt.title('Scatter Plot Example')
plt.show()

### [5] Stack Plots

In [ ]:
idxes = [ 1,  2,  3,  4,  5,  6,  7,  8,  9]
arr1  = [23, 40, 28, 43,  8, 44, 43, 18, 17]
arr2  = [17, 30, 22, 14, 17, 17, 29, 22, 30]
arr3  = [15, 31, 18, 22, 18, 19, 13, 32, 39]

# Adding legend for stack plots is tricky.
plt.plot([], [], color='r', label = 'D 1')
plt.plot([], [], color='g', label = 'D 2')
plt.plot([], [], color='b', label = 'D 3')

plt.stackplot(idxes, arr1, arr2, arr3, colors= ['r', 'g', 'b'])
plt.title('Stack Plot Example')
plt.legend()
plt.show()

### [6] Pie Chart aka Pita bar

In [ ]:
import matplotlib.pyplot as plt

labels = 'Ne', 'Ne - samo u žutoj boji'
sections = [80, 20]
colors = ['c', 'y']

plt.pie(sections, labels=labels, colors=colors,
        startangle=90,
        explode = (0, 0.1),
        autopct = '%1.2f%%')

plt.axis('equal') # Try commenting this out.
plt.title('Je li se ovo predavanje zaista dogodilo?')
plt.show()

### [7] Fill i alpha

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Fills and Alpha Example")
plt.show()

### [8] Subplotting 

Using subplots

In [ ]:
fig, ax = plt.subplots(2, 2)

ax[0, 0].plot(np.random.random(10), color = 'r') #row=0, col=0
ax[1, 0].plot(np.random.random(10), color = 'b') #row=1, col=0
ax[0, 1].plot(np.random.random(10), color = 'g') #row=0, col=1
ax[1, 1].plot(np.random.random(10), color = 'k') #row=1, col=1
plt.show()

Korištenje figure-a

In [ ]:
fig = plt.figure()
ax1 = fig.add_axes([0.1, 0.5, 0.8, 0.4], ylim=(-1.2, 1.2))
ax2 = fig.add_axes([0.1, 0.1, 0.8, 0.4], ylim=(-1.2, 1.2))

x = np.linspace(0, 10)
ax1.plot(np.sin(x))
ax2.plot(np.cos(x))

plt.show()

In [ ]:
fig = plt.figure()
#fig.subplots_adjust(hspace=0.4, wspace=0.4)

for i in range(1, 7):
    plt.subplot(2, 3, i)
    plt.text(0.5, 0.5, str((2, 3, i)),fontsize=18, ha='center')

Korištenje subplot2grid

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def random_plots():
  xs = []
  ys = []
  
  for i in range(20):
    x = i
    y = np.random.randint(10)
    
    xs.append(x)
    ys.append(y)
  
  return xs, ys

fig = plt.figure()
ax1 = plt.subplot2grid((5, 2), (0, 0), rowspan=1, colspan=2)
ax2 = plt.subplot2grid((5, 2), (1, 0), rowspan=3, colspan=2)
ax3 = plt.subplot2grid((5, 2), (4, 0), rowspan=1, colspan=1)
ax4 = plt.subplot2grid((5, 2), (4, 1), rowspan=1, colspan=1)

x, y = random_plots()
ax1.plot(x, y)

x, y = random_plots()
ax2.plot(x, y)

x, y = random_plots()
ax3.plot(x, y)

x, y = random_plots()
ax4.plot(x, y)

plt.tight_layout()
plt.show()

## VJEŽBE

#### 1. Generirajte numpy niz koji sadrži 50 prirodnih brojeva. Generirajte drugi niz koji je korijen svakog elementa prvog niza.

> #### Ovo bi trebali napraviti na dva načina: <br/>  (i) Korištenjem math.sqrt() funkcije računanjem drugog korijena eksplicitno za svaki element korištenjem for petlje <br/> (ii) Korištenjem numpy ufunc np.sqrt().   

#### Koristite python timeit funkciju da biste izračunali i isprintali vrijeme poterbno za izvršavanje (i) i (ii). Primjetite ubrzanje/usporenje u slučaju (ii).

In [3]:
import math
import timeit

In [26]:
array = np.random.randint(1,1000,50)

(1) math

In [27]:
def getSquaredArray():
    newArray = []
    for item in array:
        newArray.append(round(math.sqrt(item), 2))
    return newArray
%timeit -r 4 -n 100 getSquaredArray()

75.6 µs ± 21.8 µs per loop (mean ± std. dev. of 4 runs, 100 loops each)


In [28]:
print(getSquaredArray())

[21.95, 31.1, 15.13, 16.79, 9.8, 19.03, 22.36, 30.32, 31.38, 23.9, 21.28, 6.86, 18.38, 15.87, 22.65, 2.0, 30.59, 7.28, 19.52, 18.73, 29.68, 14.04, 28.74, 22.87, 23.28, 30.56, 20.42, 24.08, 30.27, 21.35, 16.19, 21.31, 18.19, 25.02, 15.26, 11.53, 24.23, 30.68, 18.89, 24.62, 26.53, 20.93, 25.38, 24.47, 19.57, 16.34, 22.69, 31.32, 26.15, 27.24]


(2) np

In [29]:
def getSquaredArrayNP():
    return np.square(array)
%timeit -r 4 -n 100 getSquaredArrayNP()

1.3 µs ± 93.5 ns per loop (mean ± std. dev. of 4 runs, 100 loops each)


In [30]:
print(getSquaredArrayNP())

[232324 935089  52441  79524   9216 131044 250000 844561 970225 326041
 205209   2209 114244  63504 263169     16 876096   2809 145161 123201
 776161  38809 682276 273529 293764 872356 173889 336400 839056 207936
  68644 206116 109561 391876  54289  17689 344569 885481 127449 367236
 495616 191844 414736 358801 146689  71289 265225 962361 467856 550564]


#### 2. Kreirajte niz veličine 10 x 10 sa svim elementima jednakim 0 kroz liniju koda te zamijenite svaki element na 'granici' niza sa brojem 100

In [46]:
zero2Darray = np.pad(np.full((10, 10), np.zeros(10)), pad_width=1, constant_values=100)

In [47]:
print(zero2Darray)

[[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]
 [100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]]


####  3. Kreirajte 1D niz nasumičnih brojeva te kreirajte listu indeksa temeljen na sortiranom nizu

In [ ]:
print(np.argsort(array))

[15 11 17  4 35 21  2 34 13 30 45  3 32 12 19 38  5 18 44 26 41 10 31 29
  0  6 14 46 23 24  9 27 36 43 39 33 42 48 40 49 22 20 28  7 25 16 37  1
 47  8]


#### 4. Kreirajte numpy niz veličine 5 X 10 X 20 koji se sastoji od random int brojeva. Izračunajte srednju vrijednost niza preko različith osi. Nakon toga napravite sumu izračunatih srednjih vrijednosti. Kreirajte plot za svaki od tri rezultata te ih iscrtajte u obliku sublotova koji se nalaze u horizontalnom nizu. 


In [106]:
array = np.random.randint(1,100, (5,10,20), dtype=int)
x = np.mean(array, 0)
sumX = np.sum(array,0)

fig, ax = plt.subplot(3, 1)
ax[1] = plt.plot(sumX)


TypeError: subplot() takes 1 or 3 positional arguments but 2 were given

<Figure size 432x288 with 0 Axes>

### LITERATURA

1.   Datacamp NumPy [cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
2.   [numpy for MATLAB users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html)
3.  Numpy [reference](https://docs.scipy.org/doc/numpy/reference/)
4. Matplotlib [docs](https://matplotlib.org/3.1.1/api/index.html)
5. Matplotlib [tutorial](https://matplotlib.org/tutorials/index.html)


